//
//  film.swift
//  cinematch
//
//  Created by Gregory Dziedzic on 22/06/2021.
//

import Foundation

struct Film: Identifiable {
    
    var id = UUID()
    
    let nom: String
    let studio: String
    let poster: String
    let synopsis: String
    let duree: Int
    let genre: [Genre]
    let genre2: String
    let realisateur: String
    let acteur: String
    let dateSortie: Int
    let note: Int
    let ageMinimum: Int
    let trailer: String
    let trailer2: String
    let trailer3: String
    let trailer4: String
    let plateformes: [PlateformesDispo]
    let plateformesDisplay: String
    let plateformesDisplay2: String
    let seance1: String
    let seance2: String
    var concordanceCriteres=0
    let videoTrailer: String
    
}


var avengersEndgame=Film(nom: "Avengers Endgame", studio: "Walt Disney Studios", poster: "endgame", synopsis: "Thanos ayant anéanti la moitié de l’univers, les Avengers restants resserrent les rangs dans ce vingt-deuxième film des Studios Marvel, grande conclusion d’un des chapitres de l’Univers Cinématographique Marvel.", duree: 181, genre:[.action, .sciencefiction, .fantastique,.aventure], genre2: "action • science-fiction", realisateur: "Russo Brothers", acteur: "Chris Evans", dateSortie: 2019, note: 94, ageMinimum: 13, trailer: "endgame1", trailer2: "endgame2", trailer3: "endgame3",  trailer4: "endgame4", plateformes:[.netflix, .disneyplus], plateformesDisplay: "Netflix", plateformesDisplay2: "Disney", seance1: "Pathé Beaugrenelle 16h00 • 19h00", seance2: "Gaumont Alésia 15h30 • 19h30", videoTrailer: "https://sarthe.blog/CM/endgame.mp4")
var nosJoursHeureux=Film(nom: "Nos jours heureux", studio: "SND - Studios Canal", poster: "nosjoursheureux", synopsis: "Vincent Rousseau dirige pour la première fois une colonie de vacances et se retrouve plongé pendant trois semaines dans l'univers des colos avec petites histoires et gros soucis à la clef ! Dès le départ en train, les enfants sont ingérables : l'une a perdu sa valise, l'autre assomme tout le monde de questions.", duree: 103, genre:[.comedie], genre2: "comédie", realisateur: "Eric Toledano & Olivier Nakache", acteur: "Omar Sy, Jean-Paul Rove", dateSortie: 2006, note: 80, ageMinimum: 3, trailer: "nosjoursheureux1", trailer2: "nosjoursheureux2", trailer3: "",  trailer4: "",  plateformes:[.canal, .ocs], plateformesDisplay: "Canal", plateformesDisplay2: "OCS", seance1: "Pathé Vilette 12h00 • 21h00", seance2: "Gaumont Les Fauvette 14h00 • 18h00", videoTrailer: "https://sarthe.blog/CM/jours.mp4")
var underground=Film(nom: "6 Underground", studio: "Bay Films - Netflix", poster: "sixunderground", synopsis: "Le meilleur avantage d'être mort c'est la liberté qu'elle vous procure. Soudainement, vous n'êtes plus obligé de répondre à quiconque ou d'obéir aux règles de la société. Dans ce film, un mystèrieux milliardaire réunit cinq personnes qui ont simulé leur propre mort afin d'augmenter leur champ d'action pour accomplir une mission. Ils ont pour objectif d'éliminer les plus puissants criminels et dictateurs dans le monde.", duree: 120, genre:[.action], genre2: "action", realisateur: "Michael Bay", acteur: "Ryan Reynolds, Mélanie Laurent", dateSortie: 2019, note: 33, ageMinimum: 16, trailer: "6underground1", trailer2: "6underground2", trailer3: "",  trailer4: "", plateformes:[.netflix, .primeVideo], plateformesDisplay: "Netflix", plateformesDisplay2: "Prime", seance1: "Pathé Atlantis 15h00 • 20h00", seance2: "Gaumont Angers 11h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/6Underground.mp4")
var hitch=Film(nom: "Hitch - Expert en séduction", studio: "Columbia Pictures", poster: "hitch", synopsis: "Alex Hitchens, dit Hitch, exerce un métier particulier. Il coache, en effet, des hommes qui rêvent de séduire des femmes extraordinaires. Ses méthodes sont souvent couronnées de succès. Pourtant, Hitch ne croit pas en l'amour. Sa vision des choses change lorsqu'il rencontre Sara, une jeune journaliste.", duree: 120, genre:[.comedie, .romance], genre2: "comédie • romance", realisateur: "Andy Tennant", acteur: "Will Smith, Eva Mendes", dateSortie: 2005, note: 68, ageMinimum: 7, trailer: "hitch1", trailer2: "hitch2", trailer3: "",  trailer4: "", plateformes:[.netflix, .canal], plateformesDisplay: "Netflix", plateformesDisplay2: "Canal", seance1: "Pathé Carré de Soie 10h30 • 21h00", seance2: "Pathé Aéroville 10h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/Hitch.mp4")
var retourverslefutur=Film(nom: "Retour vers le futur", studio: "Universal Pictures", poster: "retourverslefutur", synopsis: "Le jeune Marty McFly mène une existence anonyme, auprès de sa petite amie Jennifer, seulement troublée par sa famille en crise et un proviseur qui serait ravi de l'expulser du lycée. Ami de l'excentrique professeur Emmett Brown, il l'accompagne tester sa nouvelle expérience : le voyage dans le temps via une DeLorean modifiée. La démonstration tourne mal : des trafiquants d'armes débarquent et assassinent le scientifique.", duree: 116, genre:[.sciencefiction, .aventure], genre2: "aventure • science-ficton", realisateur: "Robert Zemeckis", acteur: "Michael J Fox", dateSortie: 1985, note: 96, ageMinimum: 13, trailer: "retourverslefutur1", trailer2: "retourverslefutur2", trailer3: "",  trailer4: "", plateformes:[.netflix, .primeVideo], plateformesDisplay: "Netflix", plateformesDisplay2: "Prime", seance1: "Gaumont Wilson 16h00 • 21h30", seance2: "Gaumont Labège 12h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/RetourVersLeFutur.mp4")
var intouchables = Film(nom: "Intouchables", studio:"Gaumont", poster:"intouchables", synopsis: "Tout les oppose et il était peu probable qu'ils se rencontrent un jour, et pourtant. Philippe, un riche aristocrate devenu tétraplégique après un accident de parapente va engager Driss, un jeune homme d'origine sénégalaise tout droit sorti de prison, comme auxiliaire de vie à domicile. Pourquoi lui ? Tout simplement parce qu'il ne regarde pas Philippe avec le même regard de pitié que les autres candidats.", duree: 112, genre: [.drame, .comedie], genre2: "drame", realisateur: "Olivier Nakache, Eric Toledano", acteur:"Omar Sy", dateSortie: 2011, note: 75, ageMinimum: 10, trailer: "intouchables1", trailer2: "intouchables2", trailer3: "",  trailer4: "", plateformes: [.appleTV, .primeVideo], plateformesDisplay: "AppleTV", plateformesDisplay2: "Prime", seance1: "Gaumont Comédie 16h00 • 20h00", seance2: "Gaumont Montpellier Multiplexe 14h00 • 20h00", videoTrailer: "https://sarthe.blog/CM/Intouchables.mp4")
var harrypotter4 = Film(nom: "Harry Potter et la Coupe de feu", studio: "Warner Bros.", poster: "harrypotter4", synopsis: "La quatrième année à l'école de Poudlard est marquée par le Tournoi des trois sorciers. Les participants sont choisis par la fameuse coupe de feu qui est à l'origine d'un scandale. Elle sélectionne Harry Potter alors qu'il n'a pas l'âge légal requis !", duree: 157, genre: [.fantastique, .fantasy], genre2: "fantasy", realisateur: "Mike Newell", acteur: "Daniel Radcliffe, Emma Watson", dateSortie: 2005, note: 88, ageMinimum: 13, trailer: "harrypotter4-1", trailer2: "harrypotter4-1", trailer3: "",  trailer4: "", plateformes: [.primeVideo, .ocs], plateformesDisplay: "Prime", plateformesDisplay2: "OCS", seance1: "Pathé Archamps 16h00 • 19h00", seance2: "Ciné Marivaux 16h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/HarryPotter4.mp4")
var gladiator=Film(nom: "Gladiator", studio: "Universal Pictures", poster: "gladiator", synopsis: "Le général romain Maximus est le plus fidèle soutien de l'empereur Marc Aurèle, qu'il a conduit de victoire en victoire. Jaloux du prestige de Maximus, et plus encore de l'amour que lui voue l'empereur, le fils de Marc Aurèle, Commode, s'arroge brutalement le pouvoir, puis ordonne l'arrestation du général et son exécution. Maximus échappe à ses assassins, mais ne peut empêcher le massacre de sa famille. Capturé par un marchand d'esclaves, il devient gladiateur et prépare sa vengeance.", duree: 194, genre:[.aventure, .historique, .action, .drame], genre2: "action • drame", realisateur: "Ridley Scott", acteur: "Russel Crowe", dateSortie: 2000, note: 77, ageMinimum: 18, trailer: "gladiator1", trailer2: "gladiator2", trailer3: "",  trailer4: "", plateformes:[.canal, .primeVideo], plateformesDisplay: "Canal", plateformesDisplay2: "Prime", seance1: "Pathé Beaugrenelle 16h00 • 19h00", seance2: "Pathé Beaugrenelle 16h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/GLADIATOR.mp4")
var shrek=Film(nom: "Shrek", studio: "Dreamworks SKG", poster: "shrek", synopsis: "Shrek, un ogre verdâtre, découvre de petites créatures agaçantes qui errent dans son marais. Shrek se rend alors au château du seigneur Lord Farquaad, qui aurait soi-disant expulsé ces êtres de son royaume. Ce dernier souhaite épouser la princesse Fiona, mais celle-ci est retenue prisonnière par un abominable dragon. Il lui faut un chevalier assez brave pour secourir la belle. Shrek accepte d'accomplir cette mission.", duree: 90, genre:[.animation, .aventure], genre2: "animation • comédie", realisateur: "Andrew Adamson", acteur: "Mike Myers", dateSortie: 2001, note: 88, ageMinimum: 7, trailer: "shrek1", trailer2: "shrek2", trailer3: "",  trailer4: "", plateformes:[.ocs, .netflix], plateformesDisplay: "Netflix", plateformesDisplay2: "OCS", seance1: "Pathé Saran 10h00 • 16h00", seance2: "Pathé Orléans 16h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/Shrek.mp4")
var thematrix=Film(nom: "The Matrix", studio: "Warner Bros.", poster: "thematrix", synopsis: "Programmeur anonyme dans un service administratif le jour, Thomas Anderson devient Neo la nuit venue. Sous ce pseudonyme, il est l'un des pirates les plus recherchés du cyber-espace. À cheval entre deux mondes, Neo est assailli par d'étranges songes et des messages cryptés provenant d'un certain Morpheus. Celui-ci l'exhorte à aller au-delà des apparences et à trouver la réponse à la question qui hante constamment ses pensées : qu'est-ce que la Matrice ?", duree: 130, genre:[.action, .sciencefiction, .fantastique,.aventure, .anticipation], genre2: "science-fiction • aventure", realisateur: "Les Wachowski", acteur: "Keanu Reeves", dateSortie: 1999, note: 88, ageMinimum: 13, trailer: "thematrix1", trailer2: "thematrix2", trailer3: "", trailer4: "", plateformes:[.netflix, .primeVideo], plateformesDisplay: "Netflix", plateformesDisplay2: "Prime", seance1: "Pathé Docks 76 11h00 • 21h00", seance2: "Gaumont Grand Quevilly 16h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/The Matrix.mp4")
var bigfish=Film(nom: "Big Fish", studio: "Columbia Pictures", poster: "bigfish", synopsis: "L'histoire à la fois drôle et poignante d'Edward Bloom, un père débordant d'imagination, et de son fils William. Ce dernier retourne au domicile familial après l'avoir quitté longtemps auparavant, pour être au chevet de son père, atteint d'un cancer. Il souhaite mieux le connaître et découvrir ses secrets avant qu'il ne soit trop tard. L'aventure débutera lorsque William tentera de discerner le vrai du faux dans les propos de son père mourant.", duree: 125, genre:[.drame], genre2: "drame", realisateur: "Tim Burton", acteur: "Ewan McGregor", dateSortie: 2004, note: 75, ageMinimum: 13, trailer: "bigfish1", trailer2: "bigfish2", trailer3: "", trailer4: "", plateformes:[.primeVideo, .ocs], plateformesDisplay: "Prime", plateformesDisplay2: "OCS", seance1: "Pathé Les Rives de l'Orne 16h00 • 19h00", seance2: "Gaumont Docks Vauban 16h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/Bigfish.mp4")
var titanic=Film(nom: "Titanic", studio: "20th Century Fox", poster: "titanic", synopsis: "En 1997, l'épave du Titanic est l'objet d'une exploration fiévreuse, menée par des chercheurs de trésor en quête d'un diamant bleu qui se trouvait à bord. Frappée par un reportage télévisé, l'une des rescapés du naufrage, âgée de 102 ans, Rose DeWitt, se rend sur place et évoque ses souvenirs. 1912. Fiancée à un industriel arrogant, Rose croise sur le bateau un artiste sans le sou.", duree: 195, genre:[.drame, .romance, .catastrophe], genre2: "drame", realisateur: "James Cameron", acteur: "Leonardo Di Caprio, Kate Winslet", dateSortie: 1997, note: 89, ageMinimum: 13, trailer: "titanic1", trailer2: "titanic2", trailer3: "", trailer4: "", plateformes:[.disneyplus, .canal], plateformesDisplay: "Disney", plateformesDisplay2: "Canal", seance1: "Pathé Beaugrenelle 16h00 • 19h00", seance2: "Pathé Beaugrenelle 16h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/Titanic.mp4")
var tenet=Film(nom: "Tenet", studio: "Warner Bros.", poster: "tenet", synopsis: "Le 'protagoniste' sillonne l'univers crépusculaire de l'espionnage international. Sa mission le projette dans une dimension qui dépasse le temps. Pourtant, il ne s'agit pas d'un voyage dans le temps, mais d'un renversement temporel.", duree: 150, genre: [.sciencefiction,.action,.thriller], genre2: "action • science-fiction", realisateur: "Christopher Nolan", acteur: "John David Washington", dateSortie: 2020, note: 70, ageMinimum: 13, trailer: "tenet1", trailer2: "tenet2", trailer3: "", trailer4: "", plateformes: [.ocs,.primeVideo], plateformesDisplay: "Prime", plateformesDisplay2: "OCS", seance1: "Gaumont Cité Europe 10h00 • 14h00", seance2: "Gaumont Cité Europe 16h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/TENET.mp4")
var lahaut=Film(nom: "Là-Haut", studio: "Pixar Animation Studios", poster: "lahaut", synopsis: "Un vendeur de ballons un peu bougon de 78 ans, Carl Fredricksen, craint de perdre la maison qu'il a lui-même construite. Pour y échapper, il réalise enfin le rêve de sa vie : attacher des milliers de ballons à sa maison et s'envoler vers les régions sauvages de l'Amérique du Sud.", duree: 96, genre: [.animation, .aventure, .fantastique], genre2: "animation • aventure", realisateur: "Pete Docter, Bob Peterson", acteur: "Edward Asner", dateSortie: 2009, note: 98, ageMinimum: 5, trailer: "lahaut1", trailer2: "lahaut2", trailer3: "", trailer4: "", plateformes: [.disneyplus, .canal], plateformesDisplay: "Disney", plateformesDisplay2: "Canal", seance1: "Gaumont Disney Village 10h00 • 11h00", seance2: "Gaumont Disney Village 14h00 • 16h00", videoTrailer: "https://sarthe.blog/CM/up.mp4")
var lemans66=Film(nom: "Le Mans 66", studio: "20th Century Fox", poster: "lemans66", synopsis: "Dans les années 60, les constructeurs Ford et Ferrari se livraient une guerre sans merci. À cette époque, Henry Ford II reprenait l'entreprise familiale de son grand-père avec pour objectif d'imposer les voitures américaines sur le marché européen. Il a été assisté par Lee Iacocca. La rivalité entre les deux constructeurs connue sont apogée lors des 24 heures du Mans de 1966.", duree: 152, genre: [.drame,.action], genre2: "drame • biopic", realisateur: "James Mangold", acteur: "Christian Bale, Matt Damon, Jon Bernthal", dateSortie: 2019, note: 92, ageMinimum: 13, trailer: "lemans66-1", trailer2: "lemans66-2",  trailer3: "", trailer4: "", plateformes: [.disneyplus, .ocs], plateformesDisplay: "Disney", plateformesDisplay2: "OCS", seance1: "Pathé Le Mans 10h00 • 15h00", seance2: "Pathé Angers 16h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/LeMans66.mp4")
var jurassicworld=Film(nom: "Jurassic World", studio: "20th Century Fox", poster: "jurassicworld", synopsis: "L'île Nublar accueille maintenant un parc thématique complètement fonctionnel sur les dinosaures, appelé Jurassic World. Après dix ans d'opération et un nombre de visiteurs en chute libre, une nouvelle attraction est créée dans le but d'attirer d'autres curieux, mais les résultats ne sont pas exactement ceux auxquels l'organisation s'attendait.", duree: 124, genre:[.sciencefiction, .aventure, .comedie], genre2: "science-fiction • aventure", realisateur: "Colin Trevorrow", acteur: "Chris Pratt", dateSortie: 2015, note: 71, ageMinimum: 7, trailer: "jurassicworld1", trailer2: "jurassicworld2",  trailer3: "", trailer4: "", plateformes:[.disneyplus, .netflix], plateformesDisplay: "Dinsey", plateformesDisplay2: "Netflix", seance1: "Gaumont Rennes 16h00 • 19h00", seance2: "Multiplexe Liberté 14h00 • 20h00", videoTrailer: "https://sarthe.blog/CM/JurassicWorld.mp4")
var skyfall=Film(nom: "007 Skyfall", studio: "EON Productions", poster: "skyfall", synopsis: "Laissé pour mort après une mission en Turquie qui a tourné au désastre, l'agent britannique James Bond, nom de code 007, réapparaît à Londres lorsqu'il apprend par les informations d'un journal télévisé qu'un attentat a été commis contre le M16. Cet événement ébranle considérablement l'autorité de la directrice M.", duree: 143, genre: [.action,.thriller], genre2: "thriller • espionnage", realisateur: "Sam Mendes", acteur: "Daniel Craig", dateSortie: 2012, note: 92, ageMinimum: 13, trailer: "skyfall1", trailer2: "skyfall2",  trailer3: "", trailer4: "", plateformes: [.appleTV,.netflix], plateformesDisplay: "AppleTV", plateformesDisplay2: "Netflix", seance1: "Pathé Brumath 16h00 • 19h00", seance2: "Gaumont Amnéville 16h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/Skyfall.mp4")
var getout=Film(nom: "Get Out", studio: "Blumhouse Productions", poster: "getout", synopsis: "Maintenant que Chris et sa copine Rose vont rencontrer leurs parents respectifs, elle l'invite dans la résidence secondaire de sa famille pour un week-end. D'abord Chris comprend que le comportement un peu étrange de la famille de Rose est lié au fait qu'il est noir et qu'elle est blanche. Cependant, il découvre que la vérité est bien plus dérangeante.", duree: 104, genre: [.horreur], genre2: "horreur", realisateur: "Jordan Peele", acteur: "Daniel Kaluuya, Allison Williams", dateSortie: 2017, note: 98, ageMinimum: 12, trailer: "getout1", trailer2: "getout2", trailer3: "getout3", trailer4: "getout3", plateformes: [.canal, .ocs], plateformesDisplay: "Canal", plateformesDisplay2: "OCS", seance1: "Pathé Beaugrenelle 10h00 • 22h00", seance2: "Gaumont Convention 16h00 • 19h00", videoTrailer: "https://sarthe.blog/CM/GetOut.mp4")
var thebanker=Film(nom: "The Banker", studio: "Romulus Entertainment - Apple", poster: "thebanker", synopsis: "Bernard Garrett rêve de faire fortune dans l'immobilier. Lorsqu'il rencontre Joe Morris, les deux hommes voient en grand, mais le racisme les empêchent de réaliser leurs projets. C'est alors qu'ils décident de défient les lois raciales, en vigueur dans les années 1950 aux États-Unis en recrutant un employé blanc, Matt Steiner, et décident de l'installer à la tête de leur entreprise.", duree: 120, genre: [.drame,.historique],genre2: "drame", realisateur: "George Nolfi", acteur: "Anthony Mackie, Samuel L. Jackson, Nicholas Hoult", dateSortie: 2020, note: 90, ageMinimum: 6, trailer: "thebanker1", trailer2: "thebanker2", trailer3: "thebanker3", trailer4: "thebanker4", plateformes: [.appleTV, .ocs], plateformesDisplay: "AppleTV", plateformesDisplay2: "OCS", seance1: "Gaumont Champs-Élysées 16h00 • 19h00", seance2: "Gaumont Parnasse 14h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/TheBanker.mp4")

var thedarkknight=Film(nom: "The Dark Knight :\n Le Chevalier noir", studio: "Warner Bros.", poster: "thedarkknight", synopsis: "Batman est plus que jamais déterminé à éradiquer le crime organisé qui sème la terreur en ville. Epaulé par le lieutenant Jim Gordon et par le procureur de Gotham City, Harvey Dent, Batman voit son champ d'action s'élargir. La collaboration des trois hommes s'avère très efficace et ne tarde pas à porter ses fruits jusqu'à ce qu'un criminel redoutable vienne plonger la ville de Gotham City dans le chaos.", duree: 153, genre: [.action], genre2: "action • super-héros", realisateur: "Christopher Nolan", acteur: "Christian Bale", dateSortie: 2008, note: 94, ageMinimum: 10, trailer: "thedarkknight1", trailer2: "thedarkknight2", trailer3: "", trailer4: "", plateformes: [.netflix, .primeVideo], plateformesDisplay: "Netflix", plateformesDisplay2: "Prime", seance1: "Gaumont Wilson 16h00 • 21h30", seance2: "Gaumont Labège 12h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/thedarkknight.mp4")

var walle=Film(nom: "WALL·E", studio: "Pixar Animation Studios", poster: "walle", synopsis: "Wall E, un petit robot, est le dernier être sur Terre ! 700 ans plus tôt, l'humanité a déserté notre planète en lui laissant le soin de nettoyer la Terre. Mais Wall E a développé un petit défaut technique : une forte personnalité ! Curieux et indiscret, il est surtout très seul. Sa vie va être bouleversée avec l'arrivée d'Eve, une petite robote. Wall E va tout mettre en uvre pour la séduire.", duree: 98, genre: [.animation, .anticipation, .sciencefiction, .comedie], genre2: "animation • anticipation", realisateur: "Andrew Stanton", acteur: "Ben Burt", dateSortie: 2008, note: 95, ageMinimum: 6, trailer: "walle1", trailer2: "walle2", trailer3: "", trailer4: "", plateformes: [.disneyplus, .ocs], plateformesDisplay: "Disney", plateformesDisplay2: "OCS", seance1: "Gaumont Labège 12h00 • 17h00", seance2: "Gaumont Wilson 16h00 • 21h30", videoTrailer: "https://sarthe.blog/CM/walle.mp4")

var the127h=Film(nom: "127 heures", studio: "Everest Entertainment", poster: "the127h", synopsis: "Le 26 avril 2003, Aron Ralston, jeune homme de 27 ans, se met en route pour une randonnée dans les gorges de l'Utah. Il est seul et n'a prévenu personne de son excursion. Alpiniste expérimenté, il collectionne les plus beaux sommets de la région. Pourtant, au fin fond d'un canyon reculé, l'impensable survient : au-dessus de lui un rocher se détache et emprisonne son bras dans le mur de rocaille.", duree: 94, genre: [.drame, .aventure], genre2: "drame • aventure", realisateur: "Danny Boyle", acteur: "James Franco", dateSortie: 2010, note: 93, ageMinimum: 10, trailer: "the127h1", trailer2: "the127h2", trailer3: "", trailer4: "", plateformes: [.canal, .netflix], plateformesDisplay: "Netflix", plateformesDisplay2: "Canal", seance1: "Gaumont Wilson 16h00 • 21h30", seance2: "Gaumont Labège 12h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/the127h.mp4")

var marchedelempereur=Film(nom: "La Marche de l'empereur", studio: "Bonne Pioche", poster: "marchedelempereur", synopsis: "L'histoire des manchots empereurs et de leur cycle de reproduction est unique au monde. Elle mêle amour, drame, courage et aventure au coeur de l'Antarctique, région la plus isolée et inhospitalière de la planète. Un scénario offert par la nature, qui se perpétue depuis des millénaires et que les hommes n'ont découvert qu'au début du XXème siècle.", duree: 94, genre: [.documentaire], genre2: "documentaire", realisateur: "Luc Jacquet", acteur: "Romane Bohringer", dateSortie: 2005, note: 94, ageMinimum: 6, trailer: "marchedelempereur1", trailer2: "marchedelempereur2", trailer3: "", trailer4: "", plateformes: [.canal, .ocs], plateformesDisplay: "Canal", plateformesDisplay2: "OCS", seance1: "Gaumont Labège 12h00 • 17h00", seance2: "Gaumont Wilson 16h00 • 21h30", videoTrailer: "https://sarthe.blog/CM/marchedelempereur.mp4")

var troie=Film(nom: "Troie", studio: "Warner Bros.", poster: "troie", synopsis: "Dans la Grèce antique, l'enlèvement d'Hélène, reine de Sparte, par Paris, prince de Troie, est une insulte que le roi Ménélas ne peut supporter. L'honneur familial étant en jeu, Agamemnon, frère de Ménélas et puissant roi de Mycènes, réunit toutes les armées grecques afin de faire sortir Hélène de Troie. L'issue de la guerre de Troie dépendra notamment d'un homme, Achille. Arrogant, rebelle, et réputé invicible, celui-ci n'a d'attache pour rien ni personne si ce n'est sa propre gloire.", duree: 163, genre: [.peplum, .action], genre2: "péplum • action", realisateur: "Wolfgang Petersen", acteur: "Brad Pitt", dateSortie: 2004, note: 54, ageMinimum: 10, trailer: "troie1", trailer2: "troie2", trailer3: "", trailer4: "", plateformes: [.netflix, .primeVideo], plateformesDisplay: "Netflix", plateformesDisplay2: "Prime", seance1: "Gaumont Wilson 16h00 • 21h30", seance2: "Gaumont Labège 12h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/troie.mp4")

var maskdezorro=Film(nom: "Le Masque de Zorro", studio: "TriStar Pictures", poster: "maskdezorro", synopsis: "Zorro, le justicier masqué, vient une fois encore de s'opposer avec succès aux plans de Don Rafael Montero, le gouverneur espagnol de la Californie. Mais le héros, alias Don Diego de la Vega, se fait vieux : il aspire à une vie plus calme auprès de sa femme Esperanza et de sa fillette Elena.", duree: 136, genre: [.action, .aventure,.romance], genre2: "aventure • romance", realisateur: "Martin Campbell", acteur: "Antonio Banderas", dateSortie: 1998, note: 83, ageMinimum: 10, trailer: "maskdezorro1", trailer2: "maskdezorro2", trailer3: "", trailer4: "", plateformes: [.appleTV, .primeVideo], plateformesDisplay: "Prime", plateformesDisplay2: "AppleTV", seance1: "Gaumont Labège 12h00 • 17h00", seance2: "Gaumont Wilson 16h00 • 21h30", videoTrailer: "https://sarthe.blog/CM/maskdezorro.mp4")

var benhur=Film(nom: "Ben-Hur", studio: "Metro-Goldwyn-Mayer", poster: "benhur", synopsis: "Jérusalem au Ier siècle. Judah Ben-Hur, prince de Judée, retrouve son ami d'enfance Messala, venu prendre la tête de la garnison romaine de Jérusalem. Mais il refuse la proposition de Messala de le rejoindre et préfère rester fidèle à son peuple. Messala ne le supporte pas. Alors que le gouverneur Gratus parade en ville, une tuile tombe du toit de Ben-Hur. Messala sait son ami innocent, mais le condamne aux galères.", duree: 214, genre: [.peplum], genre2: "péplum", realisateur: "William Wyler", acteur: "Charlton Heston", dateSortie: 1959, note: 86, ageMinimum: 10, trailer: "benhur1", trailer2: "benhur2", trailer3: "", trailer4: "", plateformes: [.appleTV, .netflix], plateformesDisplay: "Netflix", plateformesDisplay2: "AppleTV", seance1: "Gaumont Wilson 16h00 • 21h30", seance2: "Gaumont Labège 12h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/benhur.mp4")

var budapesthotel=Film(nom: "The Grand Budapest Hotel", studio: "American Empirical Pictures", poster: "budapesthotel", synopsis: "Zero Mustafa, jeune réfugié politique venu de Salim-al-Jabat, réussit à se faire engager comme lobby boy au Grand Budapest Hotel, une institution située dans les montagnes de la république de Zubrowka. Le concierge de l'établissement, l'élégant M. Gustave, qui veille sur ce mythique palace, le prend sous son aile. Ensemble, ils se rendent au domicile de Mme D., une habituée du Grand Budapest.", duree: 99, genre: [.comedie, .drame, .aventure], genre2: "comédie • drame", realisateur: "Wes Anderson", acteur: "Ralph Fiennes", dateSortie: 2014, note: 92, ageMinimum: 10, trailer: "budapesthotel1", trailer2: "budapesthotel2", trailer3: "", trailer4: "", plateformes: [.ocs, .appleTV], plateformesDisplay: "OCS", plateformesDisplay2: "AppleTV", seance1: "Gaumont Labège 12h00 • 17h00", seance2: "Gaumont Wilson 16h00 • 21h30", videoTrailer: "https://sarthe.blog/CM/budapesthotel.mp4")

var insaisissables=Film(nom: "Insaisissables", studio: "Summit Entertainment", poster: "insaisissables", synopsis: "Les Quatre Cavaliers, un groupe de brillants magiciens et illusionnistes, vient de donner deux spectacles de magie époustouflants : le premier en braquant une banque sur un autre continent, le deuxième en transférant la fortune d'un banquier véreux sur les comptes en banque du public. Deux agents spéciaux du FBI et d'Interpol sont déterminés à les arrêter avant qu'ils ne mettent à exécution leur promesse de réaliser des braquages encore plus audacieux.", duree: 115, genre: [.thriller], genre2: "thriller", realisateur: "Louis Leterrier", acteur: "Jesse Eisenberg", dateSortie: 2013, note: 50, ageMinimum: 10, trailer: "insaisissables1", trailer2: "insaisissables2", trailer3: "", trailer4: "", plateformes: [.netflix, .primeVideo], plateformesDisplay: "Netflix", plateformesDisplay2: "Prime", seance1: "Gaumont Wilson 16h00 • 21h30", seance2: "Gaumont Labège 12h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/insaisissables.mp4")

var freesolo=Film(nom: "Free Solo", studio: "National Geographic ", poster: "freesolo", synopsis: "Les mises en garde de ses amis, de ses proches et de sa petite amie n'y auront rien fait. Alex Honnold, meilleur grimpeur en solo intégral du monde, n'est pas prêt à renoncer à son défi. Nous le suivrons lors de sa préparation mentale et physique à l'aventure la plus ambitieuse de sa vie : l'ascension sans aucune corde ni équipement de sécurité d'El Capitan, paroi rocheuse de près d'un kilomètre située dans le parc national de Yosemite, aux États-Unis.", duree: 100, genre: [.documentaire], genre2: "documentaire", realisateur: "Elizabeth Chai Vasarhelyi", acteur: "Elizabeth Chai Vasarhelyi", dateSortie: 2018, note: 90, ageMinimum: 10, trailer: "freesolo1", trailer2: "freesolo2", trailer3: "", trailer4: "", plateformes: [.disneyplus, .ocs], plateformesDisplay: "Disney", plateformesDisplay2: "OCS", seance1: "Gaumont Labège 12h00 • 17h00", seance2: "Gaumont Wilson 16h00 • 21h30", videoTrailer: "https://sarthe.blog/CM/freesolo.mp4")

var cask=Film(nom: "Ça", studio: "New Line Cinema", poster: "cask", synopsis: "À Derry, dans le Maine, sept gamins ayant du mal à s'intégrer se sont regroupés au sein du Club des Ratés. Rejetés par leurs camarades, ils sont les cibles favorites des gros durs de l'école. Ils ont aussi en commun d'avoir éprouvé leur plus grande terreur face à un terrible prédateur métamorphe qu'ils appellent Ça.", duree: 135, genre: [.horreur], genre2: "horreur", realisateur: "Andrés Muschietti", acteur: "Jaeden Lieberher", dateSortie: 2017, note: 86, ageMinimum: 12, trailer: "cask1", trailer2: "cask2", trailer3: "", trailer4: "", plateformes: [.canal, .primeVideo], plateformesDisplay: "Prime", plateformesDisplay2: "Canal", seance1: "Gaumont Wilson 16h00 • 21h30", seance2: "Gaumont Labège 12h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/cask.mp4")

var avatar=Film(nom: "Avatar", studio: "20th Century Fox", poster: "avatar", synopsis: "Malgré sa paralysie, Jake Sully, un ancien marine immobilisé dans un fauteuil roulant, est resté un combattant au plus profond de son être. Il est recruté pour se rendre à des années-lumière de la Terre, sur Pandora, où de puissants groupes industriels exploitent un minerai rarissime destiné à résoudre la crise énergétique sur Terre.", duree: 162, genre: [.sciencefiction], genre2: "science-fiction", realisateur: "James Cameron", acteur: "Sam Worthington", dateSortie: 2009, note: 82, ageMinimum: 10, trailer: "avatar1", trailer2: "avatar2", trailer3: "", trailer4: "", plateformes: [.appleTV, .disneyplus], plateformesDisplay: "Disney", plateformesDisplay2: "AppleTV", seance1: "Gaumont Labège 12h00 • 17h00", seance2: "Gaumont Wilson 16h00 • 21h30", videoTrailer: "https://sarthe.blog/CM/avatar.mp4")

var supersizeme=Film(nom: "Super Size Me", studio: "The Con", poster: "supersizeme", synopsis: "Presque tout le monde mange des hamburgers de temps en temps. Et si on en mangeait trois fois par jour pendant un mois ? Morgan Spurlock l'a fait, et uniquement chez McDonald's.", duree: 100, genre: [.documentaire], genre2: "documentaire", realisateur: "Morgan Spurlock", acteur: "Morgan Spurlock", dateSortie: 2004, note: 92, ageMinimum: 10, trailer: "supersizeme1", trailer2: "supersizeme2", trailer3: "", trailer4: "", plateformes: [.netflix, .primeVideo], plateformesDisplay: "Netflix", plateformesDisplay2: "Prime", seance1: "Gaumont Wilson 16h00 • 21h30", seance2: "Gaumont Labège 12h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/supersizeme.mp4")

var annabelle=Film(nom: "Annabelle", studio: "New Line Cinema", poster: "annabelle", synopsis: "Été 1969, John et Mia, qui attendent leur premier enfant, viennent d'emménager dans une maison à Santa Monica. John, qui ne sait comment choyer son épouse, lui a offert une poupée ancienne. La nuit suivante, ils sont sauvagement attaqués par un couple lié à une secte satanique. La police leur porte secours rapidement, abattant l'homme tandis que sa compagne se tranche la gorge, laissant couler quelques gouttes de sang dans l'oeil de la poupée.", duree: 98, genre: [.horreur], genre2: "horreur", realisateur: "John R. Leonetti", acteur: "Annabelle Wallis", dateSortie: 2014, note: 29, ageMinimum: 12, trailer: "annabelle1", trailer2: "annabelle2", trailer3: "", trailer4: "", plateformes: [.appleTV, .netflix], plateformesDisplay: "Netflix", plateformesDisplay2: "AppleTV", seance1: "Gaumont Labège 12h00 • 17h00", seance2: "Gaumont Wilson 16h00 • 21h30", videoTrailer: "https://sarthe.blog/CM/annabelle.mp4")

var django=Film(nom: "Django Unchained", studio: "Columbia Pictures", poster: "django", synopsis: "Un ancien esclave s'associe avec un chasseur de primes d'origine allemande qui l'a libéré : il accepte de traquer avec lui des criminels recherchés. En échange, il l'aidera à retrouver sa femme perdue depuis longtemps et esclave elle-aussi. Un western décoiffant.", duree: 165, genre: [.western], genre2: "western", realisateur: "Quentin Tarantino", acteur: "Jamie Foxx", dateSortie: 2012, note: 87, ageMinimum: 12, trailer: "django1", trailer2: "django2", trailer3: "", trailer4: "", plateformes: [.netflix, .primeVideo], plateformesDisplay: "Netflix", plateformesDisplay2: "Prime", seance1: "Gaumont Wilson 16h00 • 21h30", seance2: "Gaumont Labège 12h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/django.mp4")

var bladerunner=Film(nom: "Blade Runner", studio: "Warner Bros.", poster: "bladerunner", synopsis: "Dans les dernières années du 20e siècle, des milliers d'hommes et de femmes partent à la conquête de l'espace, fuyant les mégalopoles devenues insalubres. Sur les colonies, une nouvelle race d'esclaves voit le jour : les répliquants, des androïdes que rien ne peut distinguer de l'être humain. Cependant, suite à une révolte, ces derniers sont peu à peu retirés.", duree: 111, genre: [.sciencefiction, .action, .thriller], genre2: "science-fiction • thriller", realisateur: "Ridley Scott", acteur: "Harrison Ford", dateSortie: 1982, note: 90, ageMinimum: 12, trailer: "bladerunner1", trailer2: "bladerunner2", trailer3: "", trailer4: "", plateformes: [.primeVideo, .canal], plateformesDisplay: "Prime", plateformesDisplay2: "Canal", seance1: "Gaumont Labège 12h00 • 17h00", seance2: "Gaumont Wilson 16h00 • 21h30", videoTrailer: "https://sarthe.blog/CM/bladerunner.mp4")

var cuirassepotemkine=Film(nom: "Le Cuirassé Potemkine", studio: "Goskino", poster: "cuirassepotemkine", synopsis: "Un épisode de la Révolution russe de 1905 : l’équipage d’un cuirassé, brimé par ses officiers, se mutine et prend le contrôle du navire. Arrivés à Odessa, les marins sympathisent avec les habitants qui se font brutalement réprimer par l’armée tsariste…", duree: 68, genre: [.drame, .historique], genre2: "drame • historique", realisateur: "Sergueï Eisenstein", acteur: "Alexandre Antonov", dateSortie: 1925, note: 100, ageMinimum: 10, trailer: "cuirassepotemkine1", trailer2: "cuirassepotemkine2", trailer3: "", trailer4: "", plateformes: [.primeVideo, .appleTV], plateformesDisplay: "Prime", plateformesDisplay2: "AppleTV", seance1: "Gaumont Wilson 16h00 • 21h30", seance2: "Gaumont Labège 12h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/cuirassepotemkine.mp4")

var autantenemportelevent=Film(nom: "Autant en emporte le vent", studio: "Metro-Goldwyn-Mayer", poster: "autantenemportelevent", synopsis: "En Georgie, en 1861, Scarlett O'Hara est une jeune femme fière et volontaire de la haute société sudiste. Courtisée par tous les bons partis du pays, elle n'a d'yeux que pour Ashley Wilkes malgré ses fiançailles avec sa douce et timide cousine, Melanie Hamilton. Scarlett est pourtant bien décidée à le faire changer d'avis, mais à la réception des Douze Chênes c'est du cynique Rhett Butler qu'elle retient l'attention...", duree: 243, genre: [.drame, .romance], genre2: "drame • romance", realisateur: "Victor Fleming", acteur: "Vivien Leigh", dateSortie: 1939, note: 90, ageMinimum: 10, trailer: "autantenemportelevent1", trailer2: "autantenemportelevent2", trailer3: "", trailer4: "", plateformes: [.primeVideo, .canal], plateformesDisplay: "Prime", plateformesDisplay2: "Canal", seance1: "Gaumont Labège 12h00 • 17h00", seance2: "Gaumont Wilson 16h00 • 21h30", videoTrailer: "https://sarthe.blog/CM/autantenemportelevent.mp4")

var bowlingcolumbine=Film(nom: "Bowling for Columbine", studio: "Dog Eat Dog Films", poster: "bowlingcolumbine", synopsis: "Michael Moore enquête sur la violence provoquée par les armes à feu aux Etats-Unis. Son point de départ est la tragédie du lycée Columbine dans le Colorado en 1999. Des dizaines de lycéens avaient alors été assassinés par deux de leurs camarades.", duree: 114, genre: [.documentaire], genre2: "documentaire", realisateur: "Michael Moore", acteur: "Michael Moore", dateSortie: 2002, note: 95, ageMinimum: 10, trailer: "bowlingcolumbine1", trailer2: "bowlingcolumbine2", trailer3: "", trailer4: "", plateformes: [.netflix, .ocs], plateformesDisplay: "Netflix", plateformesDisplay2: "OCS", seance1: "Gaumont Wilson 16h00 • 21h30", seance2: "Gaumont Labège 12h00 • 17h00", videoTrailer: "https://sarthe.blog/CM/bowlingcolumbine.mp4")

var conan=Film(nom: "Conan le Barbare", studio: "Universal Pictures", poster: "conan", synopsis: "Le fils d'un chef de tribu assassiné par un ennemi devient gladiateur et s'engage à venger la mort de son père.", duree: 129, genre: [.fantasy, .aventure], genre2: "fantasy • aventure", realisateur: "John Milius", acteur: "Arnold Schwarzenegger", dateSortie: 1982, note: 64, ageMinimum: 12, trailer: "conan1", trailer2: "conan2", trailer3: "", trailer4: "", plateformes: [.netflix, .primeVideo], plateformesDisplay: "Netflix", plateformesDisplay2: "Prime", seance1: "Gaumont Labège 12h00 • 17h00", seance2: "Gaumont Wilson 16h00 • 21h30", videoTrailer: "https://sarthe.blog/CM/conan.mp4")
